# Generated by Django 3.1.4 on 2020-12-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
