# Generated by Django 3.1.4 on 2020-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0003_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
