# Generated by Django 3.1.4 on 2020-12-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0004_auto_20201213_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
